### ISSUE TITLE
Mysql: enum issue

### ISSUE THREAD

**Issue by LoicMahieu** [ArsenyYankovsky/typeorm-aurora-data-api-driver#109]
**Package versions and database engine type (please complete the following information):**
 - Database Engine: [postgres or mysql] mysql
 - TypeORM Version: [e.g. 0.2.32] 0.2.37
 - Driver Version [e.g. 2.0.6] 2.3.1

**Describe the bug**
When using an enum, MySQL results in syntax error.

**To Reproduce**
- Create a entity, for example User
- Which have an enum field, for example: userType: UserType
- Try to create a new entity, for exemple `getRepository(Product).create({ petType: UserType.normal })`
- An error occured:
```
UPDATE `product` SET `type` = :param_0 WHERE `id` = :param_1 -- PARAMETERS: [{"name":"param_0","value":"normal","cast":"user_type_enum"},{"name":"param_1","value":"1"}]
[0] BadRequestException: Database error code: 1064. Message: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'user_type) WHERE `externalId` = '1'' at line 1
```

We quickly fixed the issue by comment the line https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver/blob/master/src/query-transformer/mysql-query-transformer.ts#L55 :
```
cast: metadata.enumName || `${metadata.entityMetadata.tableName}_${metadata.databaseName.toLowerCase()}_enum`,
```

**Comment by coyoteecd** [comment]
I am seeing this as well after upgrade to latest typeorm/typeorm-aurora-data-api-driver.
