### ISSUE TITLE
Notice of a potential bug

### ISSUE THREAD

**Issue by TreeMan360** [ArsenyYankovsky/typeorm-aurora-data-api-driver#12]
Hey,

I am fairly confident I have found a bug as I have seen this issue crop up now in two different scenarios. When running against my local mysql docker instance I have no issues but when running against Aurora Serverless MySql I have encountered the error:

```"'param_1'' is an invalid type"```

(well, param_X)

This is my log:
```
INFO query:  SELECT `NewCompany`.`id` AS `NewCompany_id`, `NewCompany`.`name` AS `NewCompany_name`, `NewCompany`.`websiteUrl` AS `NewCompany_websiteUrl`, `NewCompany`.`numberOfEmployees` AS `NewCompany_numberOfEmployees`, `NewCompany`.`suggestedCategories` AS `NewCompany_suggestedCategories`, `NewCompany__existingCategories`.`updatedAt` AS `NewCompany__existingCategories_updatedAt`, `NewCompany__existingCategories`.`createdAt` AS `NewCompany__existingCategories_createdAt`, `NewCompany__existingCategories`.`version` AS `NewCompany__existingCategories_version`, `NewCompany__existingCategories`.`id` AS `NewCompany__existingCategories_id`, `NewCompany__existingCategories`.`name` AS `NewCompany__existingCategories_name`, `NewCompany__existingCategories`.`parentId` AS `NewCompany__existingCategories_parentId` FROM `new_company` `NewCompany` LEFT JOIN `new_company_existing_categories_company_category` `NewCompany_NewCompany__existingCategories` ON `NewCompany_NewCompany__existingCategories`.`newCompanyId`=`NewCompany`.`id` LEFT JOIN `company_category` `NewCompany__existingCategories` ON `NewCompany__existingCategories`.`id`=`NewCompany_NewCompany__existingCategories`.`companyCategoryId` WHERE (`NewCompany`.`id` IN (:param_0)) AND `NewCompany`.`id` IN (:param_1) -- PARAMETERS: [
{
    "param_0": "ccca5f74-5dbd-485c-86a1-925622aeea61",
    "param_1": [
        "ccca5f74-5dbd-485c-86a1-925622aeea61"
    ]
}
```

I am going to have to try and find some time to reproduce an example for diagnosis. However the original time I saw this error it was rather obvious - there were two parameters which were being passed in the wrong way around. It's worth noting that I am using this in conjunction with ```typeorm-transactional-cls-hooked```.

I understand this isn't a very good issue report but I wanted to at least mention it in the event this is something you have come across yourself.

I am using this driver in production so I need to resolve this as soon as possible :)

Versions:
```
    "typeorm": "^0.2.19",

    "typeorm-aurora-data-api-driver": "^1.1.4",

    "typeorm-transactional-cls-hooked": "^0.1.8"
```

**Comment by TreeMan360** [comment]
Looking at your code I have no idea how this is happening I must say

**Comment by ArsenyYankovsky** [comment]
@TreeMan360 could you please check if it still occurs with 1.1.5? I reworked the query transformation there.

**Comment by TreeMan360** [comment]
@ArsenyYankovsky Thanks for the quick response. Unfortunately I confirm I have the same issue with 1.1.6.

**Comment by ArsenyYankovsky** [comment]
@TreeMan360 If you could please provide a reproducible example that would be much easier to figure out. I'm in a process of migrating a big project to use the driver so I could hopefully reproduce it myself. I'm also not sure the query you originally posted. It has two `IN` clauses but one of the parameters in an array and the other is a string. Is that correct?

**Comment by TreeMan360** [comment]
I will try and reproduce this in an example this evening so we get get to the bottom of this.

**Comment by TreeMan360** [comment]
In a much simpler scenario with no transaction and a straighforward query:

```
UPDATE `member_pre_application` SET `appliedAt` = :param_0, `version` = `version` + 1, `updatedAt` = CURRENT_TIMESTAMP WHERE `id` IN (:param_1) -- PARAMETERS: [
{
    "param_0": "a4fd121b-cb32-11e9-a19c-02c46da11906",
    "param_1": "2019-09-18T15:45:07.036Z"
}
]

INFO "'param_1'' is an invalid type"
```

As you can see the two parameters are the wrong way around here. I will knock up an actual project with an executable example tonight but thought I would drop this in here incase any lightbulbs go off :)

**Comment by TreeMan360** [comment]
Is it because:

const quoteCharacters = ['\'', '"']

Needs a backtick?

**Comment by ArsenyYankovsky** [comment]
@TreeMan360 There seems to be several issues going on. Firstly, an array is not a supported type right now by a Data API itself. Secondly, I'm experiencing same thing with the date strings, so I'm looking into that.

**Comment by ArsenyYankovsky** [comment]
@TreeMan360 Working on fixing the Date type which is not supported currently.

**Comment by TreeMan360** [comment]
😎 thanks so much for the support on this. Great work!

**Comment by ArsenyYankovsky** [comment]
@TreeMan360 1.1.7 released with a fix. Let me know if I can close the issue.

**Comment by TreeMan360** [comment]
Will check now

**Comment by TreeMan360** [comment]
Ok so this is a little strange hence the delay.

When the update query executes now I receive no errors at all but it does not update the field and the query in my log looks the same. So it effectively now doesn't do anything :)

The select query still throws a parameter error as before.

At this point would you like me to try and put a test project together for you? I could attempt a PR but I can't help but think you would solve this faster than me. Let me know your preference but the latter will of course take me longer.

**Comment by ArsenyYankovsky** [comment]
Ideal for me would be a branch with a failing test. I think the param error could be reproduced as a unit test. The update sounds weird, could you try to reproduce it with a functional test.

**Comment by TreeMan360** [comment]
Hey, now looking at this. Do you run your own circle CI server and then always run your functional tests in that environment so you can access your serverless instance via its secretArn and resourceArn?

I have limited experience with CircleCI and I don't want to change the code so it works from my local machine if that's not aligned with your workflow.

**Comment by ArsenyYankovsky** [comment]
Yes, I'm running it on CircleCI server that has the environment variables to access the db set up.

**Comment by ArsenyYankovsky** [comment]
@TreeMan360 Got it reproduced, will see how I can fix that.

**Comment by TreeMan360** [comment]
OK thanks. I am having issues running the functional tests in CircleCI.

It connects to the database fine. I have my environment variables set correctly and a database created with the correct name.

The first ```SELECT 1``` test works and the database wake up call now occurs very quickly so that's definitely working.

I have been trying to work out why I am receiving ```'no database selected'```for the other simple queries...

```
  aurora data api > simple queries
    ✓ should do a simple select (594ms)
    ✕ should create a table and be able to query it (785ms)
    ✕ batch insert - with dates (741ms)

    BadRequestException: No database selected
```

**Comment by ArsenyYankovsky** [comment]
@TreeMan360 the misplaced parameters issue is coming from typeorm itself. Since the AuroraDataApiDriver is not an instance of MysqlDriver a lot of the query fixes are not applied. Right now I'm trying to fix that and I will submit a PR when I'm ready. Your build is probably set to use my fork of typeorm so that's why you might get these errors.

**Comment by ArsenyYankovsky** [comment]
@TreeMan360 I've submitted the PR to TypeORM https://github.com/typeorm/typeorm/pull/4779. Unfortunately, we'll have to wait for the PR to be merged and a new TypeORM version released for it to work. In the meantime you can try to use my fork of TypeORM to work.

**Comment by TreeMan360** [comment]
@ArsenyYankovsky wow those instanceof checks are hacktastic. Nice work. I will use your fork buddy. If I find anything else I will create w failing test.

Many Thanks!

**Comment by TreeMan360** [comment]
Would you mind pushing your changes into your TypeORM fork please?

**Comment by ArsenyYankovsky** [comment]
@TreeMan360 No problem. I would expect there's more things that are broken so the more the earlier we find now the better. Thanks.

**Comment by TreeMan360** [comment]
@ArsenyYankovsky JFYI the update query is now working as expected but the original select query I reported is not. I will find time to create a failing test.

**Comment by ArsenyYankovsky** [comment]
@TreeMan360 does the select give you an invalid type error or is the order of parameters wrong?

**Comment by TreeMan360** [comment]
> @TreeMan360 does the select give you an invalid type error or is the order of parameters wrong?

@ArsenyYankovsky Invalid type. I will look to create a test case for this.

**Comment by ArsenyYankovsky** [comment]
I think that's because you're trying to pass an array as a parameter which is currently not supporter by the Data API. Not sure we can do much here.

**Comment by TreeMan360** [comment]
>I think that's because you're trying to pass an array as a parameter which is currently not supporter by the Data API. Not sure we can do much here.

@ArsenyYankovsky yeah it’s odd actually as I don’t give TypeORM an array it’s doing that internally. I will investigate this tonight and report back.

**Comment by TreeMan360** [comment]
I believe I have fixed this, please see PR:

https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver/pull/17

**Comment by TreeMan360** [comment]
Just a confirmation that with ```1.1.8``` and your ```fix-update typeorm``` branch all my scenarios now work perfectly. 

Looking forward to https://github.com/typeorm/typeorm/pull/4779 getting merged into a release.

Thanks for your help @ArsenyYankovsky, much appreciated.

**Comment by ArsenyYankovsky** [comment]
@goors Could you please provide a reproducible code for that? Also make sure you're using latest versions.

**Comment by goors** [comment]
@ArsenyYankovsky after doing the update to latest typeorm (0.2.20) that param thing is ok now. With 0.2.19, or any smaller version there is that issue with params in the wrong order.

**Comment by TreeMan360** [comment]
@ArsenyYankovsky does 0.2.20 include the update-fix branch?

**Comment by ArsenyYankovsky** [comment]
@TreeMan360 sorry for the late response, yes it's merged into latest typeorm so you can use that instead of forked version.
