### ISSUE TITLE
Incorrect generated value for empty 'simple-array' attributes in aurora / postgres 

### ISSUE THREAD

**Issue by dpecos** [ArsenyYankovsky/typeorm-aurora-data-api-driver#133]
Having an attribute of type 'simple-array' like:
```
@Column({ type: 'simple-array' })
list: []
```

And setting its value to empty array:
```
entity.list = []
```

Generates the following parameter value:
```
{
    "name": "param_8",
    "value": {
      "value": ""
    }
  },
```

while it should be:
```
{
    "name": "param_8",
    "value": ""
  },
```

Using this transformer for the `simple-array` fields fixed the issue:
```
const simpleArray: ValueTransformer = {
  to: (entityValue: string[]) => (entityValue ? entityValue.join(',') : null),
  from: (databaseValue: string): string[] => {
    if (databaseValue === null || databaseValue === undefined) {
      return null;
    } else if (databaseValue.trim() === '') {
      return [];
    } else {
      return databaseValue.split(',');
    }
  },
};
```

I'm pretty sure this issue is similar to this one fixed in this PR: https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver/pull/125

**Comment by ArsenyYankovsky** [comment]
Fixed in https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver/pull/134

**Comment by ArsenyYankovsky** [comment]
@all-contributors please add @dpecos for contributing code and bug reports.
