### ISSUE TITLE
Upgrade data-api-client to 1.3.0

### ISSUE THREAD

**Issue by nskarakoc** [ArsenyYankovsky/typeorm-aurora-data-api-driver#143]
Package `data-api-client` has released `1.3.0` version 6 days ago. It has some fixes that we need to use. When do you plan to upgrade `data-api-client` from `1.2.0` to `1.3.0`?

https://github.com/jeremydaly/data-api-client/releases/tag/v1.3.0

**Comment by ArsenyYankovsky** [comment]
Fixed in 2.4.2. Feel free to submit a PR next time.
