### ISSUE TITLE
[Question] Is compatible with Aurora Serverless v2 ?

### ISSUE THREAD

**Issue by pablozandona** [ArsenyYankovsky/typeorm-aurora-data-api-driver#149]
Is compatible with Aurora Serverless v2 using Postgresql?

**Comment by juangomez-alation** [comment]
Also wondering the same

**Comment by RaviVadera** [comment]
> Is compatible with Aurora Serverless v2 using Postgresql?

I believe serverless v2 does not support data API at all.

**Comment by ArsenyYankovsky** [comment]
I just tested Aurora Serverless V2 and Data API (https://aws.amazon.com/blogs/database/introducing-the-data-api-for-amazon-aurora-serverless-v2-and-amazon-aurora-provisioned-clusters/) on my personal cluster and it generally seems to work. However, I often get this error from the database:
```
Transaction is still running a query
DatabaseErrorException: Transaction is still running a query
```
It's coming from the aws-sdk v2 so I will test again after I migrate this project into using aws-sdk v3.

**Comment by ryanmargono** [comment]
@ArsenyYankovsky any updates?

**Comment by ArsenyYankovsky** [comment]
Please read my previous comment, I tested it against a real cluster and all the tests passed. If you have any specific issues please report them in a separate ticket.

**Comment by ryanmargono** [comment]
Thanks @ArsenyYankovsky, do you have an example of the entities you used in your test?

**Comment by ArsenyYankovsky** [comment]
All entities used in tests for Postgres could be found here: https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver/tree/master/test/functional/pg/basic/entity
