### ISSUE TITLE
Does this driver library supports typeorm migrations?

### ISSUE THREAD

**Issue by vorant94** [ArsenyYankovsky/typeorm-aurora-data-api-driver#159]
Hi, there!

I am developing one of my pet projects and would like to use dockerized Postgres for local development (to make it as easy and straightforward as possible) and AWS Aurora serverless Postgres for production (to make it as cheap as possible) and I use TypeORM for connecting to the db. I see your lib serves this exact purpose to allow working with Aurora via TypeORM.

Its not clear for me if you support only runtime interactions like queries and so on or do you also support TypeORM migrations? As far as I see `DataApiDriver` class neither extends TypeORM `DataSource` class nor implements in, so it probably cannot be drop-in replacement for `DataSource` in orm config file... am I right? If so what is your recommendation to achieve both local and serverless integrations for runtime queries and non-runtime migrations?

**Comment by MaxMediaPictures** [comment]
Hey, not sure if this answers your question but maybe this helps: 

It looks like migrations were supported in the past but have stopped working properly for quite some time:
https://github.com/typeorm/typeorm/issues/8291

Also keep in mind that this library does not support AWS SDK v3, which could become an issue by the end of this year.
https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver/issues/148

In general I am wondering if this library is still maintained.

**Comment by vorant94** [comment]
turns out you need to use Aurora Data API only in case you are using Aurora Serverless 1... for Serverless 2 TypeORM works just as is... closing the issue as not relevant anymore...

**Comment by MaxMediaPictures** [comment]
I think also with Aurora V1 you can use TypeORM "out of the box" (aka via normal DB connections), the question is just: how do you want to connect to your DB instance? 
AFAIK for scaleable lambda services you have two options: RDS Proxy or Data Api. 
The data api only works with Aurora Serverless 1.
