### ISSUE TITLE
Is this library still being maintained?

### ISSUE THREAD

**Issue by MaxMediaPictures** [ArsenyYankovsky/typeorm-aurora-data-api-driver#160]
Hey everyone, 

I have been wondering if this library is still being maintained. 

There are a few open issue, like the support for the [AWS SDK 3](https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver/issues/148) or the [broken migration generation](https://github.com/typeorm/typeorm/issues/8291) that makes me wonder if it still makes sense to use this library in any new projects. 

In addition this project is based on the Data Api Client, which itself if kind of [deprecated](https://github.com/jeremydaly/data-api-client/issues/113).

What do you think?

**Comment by giovannijoao** [comment]
Any updates on this?

**Comment by ArsenyYankovsky** [comment]
Until recently, we didn't have Data API for Aurora Serverless V2. But now that[ it's announced](https://aws.amazon.com/blogs/database/introducing-the-data-api-for-amazon-aurora-serverless-v2-and-amazon-aurora-provisioned-clusters/).
I will fix the tests and make it work with the latest TypeORM. I will also organize issues a bit.
After that, I will take a look at the outstanding issues. I cannot guarantee any timeline or ETA though.
Feel free to submit a pull request in the meantime if you want some issue fixed faster, I will prioritize reviewing pull requests.

**Comment by ataravati** [comment]
@ArsenyYankovsky Has this already been implemented?
