### ISSUE TITLE
Dependency conflict when using typeorm-aurora-data-api-driver v3.0.0

### ISSUE THREAD

**Issue by zuming-liu-0929** [ArsenyYankovsky/typeorm-aurora-data-api-driver#163]
**Package versions and database engine type (please complete the following information):**
 - Database Engine: postgres
 - TypeORM Version: "^0.3.19"
 - Driver Version: "^3.0.0",

**Describe the bug**
I'm facing a conflit of dependency when using this driver with this error:
![image](https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver/assets/59730944/3af01ba5-e454-4857-b678-469bfb8e79c2)

**To Reproduce**
Here is the package.json on my side:
`
{
  "name": "project",
  "version": "0.0.1",
  "description": "Backend ,
  "author": "Squad",
  "private": true,
  "license": "UNLICENSED",
  "scripts": {
    "format": "prettier --write \"src/**/*.ts\" \"test/**/*.ts\"",
    "lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
    "build": "ts-node node_modules/.bin/nest build",
    "start:app": "nest start --entryFile=userside/userside-app/main",
    "migration:run": "npm run typeorm -- migration:run",
    "migration:revert": "npm run typeorm -- migration:revert",
    "migration:test:generate": "env NODE_ENV=test npm run typeorm -- migration:generate ./src/serverside/typeorm/migrations/$npm_config_name",
    "migration:test:run": "env NODE_ENV=test npm run typeorm -- migration:run",
    "migration:test:revert": "env NODE_ENV=test npm run typeorm -- migration:revert",
    "prepare": "husky install",
    "seed": "ts-node ./src/serverside/typeorm/seed/seed.ts"
  },
  "dependencies": {
    "@aws-sdk/client-sqs": "^3.342.0",
    "@aws-sdk/client-rds-data": "^3.490.0",
    "@faker-js/faker": "^8.3.1",
    "@nestjs/cache-manager": "^2.2.0",
    "@nestjs/common": "^9.0.0",
    "@nestjs/config": "^2.3.1",
    "@nestjs/core": "^9.0.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/passport": "^9.0.3",
    "@nestjs/platform-express": "^9.0.0",
    "@nestjs/schedule": "^2.2.2",
    "@nestjs/swagger": "^6.2.1",
    "@nestjs/typeorm": "^10.0.1",
    "aws-sdk": "^2.1542.0",
    "cache-manager": "^5.3.2",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "moment": "^2.29.4",
    "passport-azure-ad": "^4.3.4",
    "pg": "^8.9.0",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0",
    "typeorm": "^0.3.19",
    "typeorm-aurora-data-api-driver": "^3.0.0",
    "typeorm-extension": "^3.1.1"
  },
  "devDependencies": {
    "@casualbot/jest-sonar-reporter": "^2.3.1",
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0",
    "@types/express": "^4.17.13",
    "@types/jest": "29.2.4",
    "@types/node": "18.11.18",
    "@types/supertest": "^2.0.11",
    "@typescript-eslint/eslint-plugin": "^5.0.0",
    "@typescript-eslint/parser": "^5.0.0",
    "eslint": "^8.0.1",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "husky": "^8.0.3",
    "jest": "29.3.1",
    "prettier": "^2.3.2",
    "source-map-support": "^0.5.20",
    "supertest": "^6.1.3",
    "ts-jest": "29.0.3",
    "ts-loader": "^9.2.3",
    "ts-node": "^10.0.0",
    "tsconfig-paths": "4.1.1",
    "typescript": "^4.7.4"
  },
  "@casualbot/jest-sonar-reporter": {
    "outputDirectory": "coverage",
    "outputName": "sonar-report.xml",
    "relativePaths": "true"
  }
}
`

**Comment by ArsenyYankovsky** [comment]
This issue should be raised in the TypeORM repo, the version should be updated there.
