### ISSUE TITLE
Aws RDS postgress serverless

### ISSUE THREAD

**Issue by pontusab** [ArsenyYankovsky/typeorm-aurora-data-api-driver#20]
Nice lib! Getting an error like this:

```
 DataTypeNotSupportedError: Data type "timestamptz" in "AuthToken.createdAt" is not supported by "aurora-data-api" database.
```

How come `timestamptz`is not supported?

**Comment by pontusab** [comment]
I guess we need to add AuroraDataApiDriver where PostgresDriver is used too in TypeORM

**Comment by ArsenyYankovsky** [comment]
This driver only works for the MySQL right now. I guess there should be a special parameter to handle the Postgres as well in the future.

**Comment by pontusab** [comment]
Ok. I will fix that then

**Comment by KidA001** [comment]
@pontusab has PSQL support been added?

**Comment by ArsenyYankovsky** [comment]
@KidA001 Postgres support is tracked [here](https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver/issues/28)
