### ISSUE TITLE
Sync/Migrations?

### ISSUE THREAD

**Issue by yoongfook** [ArsenyYankovsky/typeorm-aurora-data-api-driver#21]
Firstly - thank you so much for your work on this. 
Does this support synchronization and migrations? If not, whats your workflow of performing these? eg. creating / dropping tables

**Comment by goors** [comment]
As far as I can see `synchronize` does not work, Is there someone with this issue as well?

**Comment by darbio** [comment]
I also have this issue. Not sure how to run migrations and synchronize through the data api.

**Comment by TreeMan360** [comment]
I use migrations without any issues. I do however locally run against MySQL running in a docker container and I generate my migrations against that and then I just use the data API in a deployed scenario where the migrations are executed.

**Comment by ArsenyYankovsky** [comment]
We are also using synchronize inside the functional tests without any issues. If you could provide a reproducible scenario I'll gladly take a look at it.

**Comment by anton-nagornyi** [comment]
I am also facing a sync issue with the serverless aurora postgres. Synchronize with dropBeforeSync === true works fine. If it is false, it tries to create tables again and fails because they already exist.

**Comment by mrvisser** [comment]
I'm also facing this issue when not using `dropBeforeSync`.
