### ISSUE TITLE
ERROR: syntax error at or near "."

### ISSUE THREAD

**Issue by idhard** [ArsenyYankovsky/typeorm-aurora-data-api-driver#22]
Hello , thanks for the driver ;) 

i'm facing a parsing error when trying to query to aurora postgresql serverless :

ERROR: syntax error at or near "."

the query is :

```
SELECT DISTINCT `distinctAlias`.`User_id` as "ids_User_id" FROM (SELECT `User`.`id` AS `User_id`, `User`.`email` AS `User_email`....
```
if i replace "`" by " " " seems to execute correctly, in my test, but not sure how to make it work generally , any help would be welcome 

thanks

**Comment by ArsenyYankovsky** [comment]
Hello, I haven't really tested the driver against postgres because the use case I started it for was for MySQL. So, currently the postgres is not supported.

It's a bit of work to make it work for postgres and requires changes in the TypeORM project itself. I can't promise any timeframe, but I will take a look at it.

**Comment by idhard** [comment]
hey , yes i reached same conclusion the driver only works for mysql, i have been playing around with it and at least managed to successfully connect to my db although when doing queries the format is incorrect.
Let me know if i can help you somehow

**Comment by mpvosseller** [comment]
I ran into the same issue. In my case I got the below error. Adding support for postgres would be great.  

```
query: SELECT DATABASE() AS `db_name`
TypeORM connection error:  BadRequestException: ERROR: syntax error at or near "`"
```

**Comment by rudieros** [comment]
Getting the same as @mpvosseller
+1 for postgres support

**Comment by ArsenyYankovsky** [comment]
I'm going to track the Postgres work [here](https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver/issues/28)
