### ISSUE TITLE
aws-sdk as dependency

### ISSUE THREAD

**Issue by elderapo** [ArsenyYankovsky/typeorm-aurora-data-api-driver#24]
I think `aws-sdk` should be added as `dependency` and not `devDependency`.

**Comment by ArsenyYankovsky** [comment]
Any particular reason it can be useful? Lambda runtime automatically provides you with aws-sdk, so adding it as a dependency will increase the size of the bundle without any benefit.

**Comment by elderapo** [comment]
When I tried to use this package from [now](https://zeit.co/download) it complained about lack of `aws-sdk`. But I guess that is the problem in `data-api-client` and not this package.

**Comment by ArsenyYankovsky** [comment]
@elderapo  What kind of complaint was that? Runtime or compile time?

**Comment by elderapo** [comment]
Runtime.

**Comment by TreeMan360** [comment]
> Runtime.

@elderapo That's very strange. ```Zeit now``` uses lambda so it should without doubt have the ```aws-sdk``` available at runtime.

What builder are you using? Are you say using ```nextjs``` in ```serverless``` deploy mode?

**Comment by elderapo** [comment]
I already moved to something different (don't have code that caused this error anymore) but I believe it happened in development `now dev`.

**Comment by TreeMan360** [comment]
Ok cool, ```now dev``` should still work as the ```aws-sdk``` should still be found in your ```node_modules``` I believe. Either way this evidently is off topic for this package.
