### ISSUE TITLE
Depends on an (out of date) fork of data-api-client

### ISSUE THREAD

**Issue by mpvosseller** [ArsenyYankovsky/typeorm-aurora-data-api-driver#27]
I noticed this project [depends](https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver/blob/d1e3e3ddcac8469284e5bd42e485b53f3ef79182/package.json#L104
) on a [fork](https://github.com/ArsenyYankovsky/data-api-client) of data-api-client instead of the [original project](https://github.com/jeremydaly/data-api-client) and is now out of date. Any reason not to just depend on the original project?

**Comment by ArsenyYankovsky** [comment]
We can't switch to the original project until https://github.com/jeremydaly/data-api-client/pull/20 is merged or the original project starts supporting the date type. I can update my fork if something is missing.

**Comment by mpvosseller** [comment]
Ah, I see. Bummer. Thanks.
