### ISSUE TITLE
Support for env variables

### ISSUE THREAD

**Issue by pzmudzinski** [ArsenyYankovsky/typeorm-aurora-data-api-driver#30]
Does this driver support passing configuration options via env variables?

e.g. `TYPEORM_SECRET_ARN`

**Comment by cklam2** [comment]
There is an example in 'test/functional/utils/create-connection.ts', [line 12](https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver/blob/d1e3e3ddcac8469284e5bd42e485b53f3ef79182/test/functional/utils/create-connection.ts#L12)

**Comment by pzmudzinski** [comment]
I know you can pass them manually in `createConnection`, but what if you want to run migrations against RDS database? Will ARNs be picked from env vars or ormconfig.json?

**Comment by cklam2** [comment]
Can switch to the [javascript](https://github.com/typeorm/typeorm/blob/master/docs/using-ormconfig.md#using-ormconfigjs) version of ormconfig for dynamic vars.
