### ISSUE TITLE
Enable override endpoint URL for local development against Docker koxudaxi/local-data-api

### ISSUE THREAD

**Issue by drissamri** [ArsenyYankovsky/typeorm-aurora-data-api-driver#34]
It would be awesome if it was possible to give a endpoint URL so you can use this package to connect to a local-data-api in Docker like https://github.com/koxudaxi/local-data-api

We use docker-compose with that docker image for local development purposes but we haven't found a way to connect to it using TypeORM and this driver. Any help is appreciated!

**Comment by ArsenyYankovsky** [comment]
@drissamri Could you try passing `endpoint` in the `serviceConfigOptions` property of your connection properties? Something like that:

```
   const connection = await createConnection({
      type: 'aurora-data-api',
      database: 'test-db',
      secretArn: 'arn:aws:secretsmanager:eu-west-1:537011205135:secret:xxxxxx/xxxxxx/xxxxxx',
      resourceArn: 'arn:aws:rds:eu-west-1:xxxxx:xxxxxx:xxxxxx',
      region: 'eu-west-1',
      serviceConfigOptions: {
        endpoint: 'http://127.0.0.1:8080',
      }
    })
```

**Comment by MarZab** [comment]
The above example works, I had trouble with `Error: connect EHOSTDOWN 169.254.169.254:80 - Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1`

Seems the AWS Handler requires the accessKeyId to be set, even if it's not using them - so the simple fix for local development:
```
serviceConfigOptions: DB_ENDPOINT ? {
        endpoint: new Endpoint(DB_ENDPOINT),
        credentials: {
          accessKeyId: 'dummy',
          secretAccessKey: 'dummy'
        }
      } : undefined,
```

**Comment by ArsenyYankovsky** [comment]
This will be fixed with the new TypeORM release.
