### ISSUE TITLE
Performance  benchmarks

### ISSUE THREAD

**Issue by tylergets** [ArsenyYankovsky/typeorm-aurora-data-api-driver#47]
Hey thank for you the world on this project, looks awesome. 

I was wondering if you have performed any benchmarks of this driver versus a default postgres connection w/ pooling, or if AWS has said anything about the data api performance.

Would be happy to assist if not!

**Comment by ArsenyYankovsky** [comment]
Hello, haven't tried anything like that, but it would be really nice to see how it fares against default connection. Especially when there's a lot of parallel lambdas calling the database.
