### ISSUE TITLE
Question: Does this support the migrations out of the box?

### ISSUE THREAD

**Issue by jgomes94** [ArsenyYankovsky/typeorm-aurora-data-api-driver#49]
I tried to the best of my ability find documentation regarding schema migrations, however, couldn't find any information regarding it.

Does this lib supports schema migrations supported by typeorm? Is there any documentation?

**Comment by ArsenyYankovsky** [comment]
@jgomes94 Yes, every functionality of TypeORM should work, including migrations. Please create an issue if something doesn't work for you.
