### ISSUE TITLE
Implement transaction handling

### ISSUE THREAD

**Issue by ArsenyYankovsky** [ArsenyYankovsky/typeorm-aurora-data-api-driver#5]

**Comment by ArsenyYankovsky** [comment]
I implemented transaction handling, however I will still keep this issue opened until https://github.com/jeremydaly/data-api-client/pull/6 gets merged

**Comment by benseitz** [comment]
@ArsenyYankovsky jeremydaly/data-api-client#6  just got merged :)

**Comment by LoicMahieu** [comment]
Hi!

I had errors related to transactions when making multiple UPDATE or CREATE.
I don't use transaction directly in my code.
Two differents errors are thrown randomly:

```
MissingRequiredParameter: Missing required key 'transactionId' in params
    at ParamValidator.fail (my-path/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (my-path/node_modules/aws-sdk/lib/param_validator.js:61:14)
    at ParamValidator.validateMember (my-path/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (my-path/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (my-path/node_modules/aws-sdk/lib/event_listeners.js:126:42)
    at Request.callListeners (my-path/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
[...]
```
or

```
BadRequestException: Transaction ARazbccQcRkr/pBmdEnDIfSI4Gbir+9KdUcN7JGr7Y3gNG6AxmKhYRUKrj4sAmnePCSgX9Izl7pb4ZsGMfw/s20AwgujvyPzpEIsYos65bCdRSpTbS37qSi45l4mDKEx6BEFVZI8hnLq50JALQOu8PKi33TtSMfe3KFNxElpILHY6jQyZun5vFg= is not found
    at Object.extractError (my-app/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (my-app/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (my-app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
```

Pressed by the time, I ended by `patch-packages`:

```diff
diff --git a/node_modules/typeorm-aurora-data-api-driver/dist/typeorm-aurora-data-api-driver.umd.js b/node_modules/typeorm-aurora-data-api-driver/dist/typeorm-aurora-data-api-driver.umd.js
index b138fa6..0bef0de 100644
--- a/node_modules/typeorm-aurora-data-api-driver/dist/typeorm-aurora-data-api-driver.umd.js
+++ b/node_modules/typeorm-aurora-data-api-driver/dist/typeorm-aurora-data-api-driver.umd.js
@@ -913,7 +913,7 @@
                             return [4 /*yield*/, this.client.query({
                                     sql: transformedQueryData.queryString,
                                     parameters: transformedQueryData.parameters,
-                                    transactionId: this.transactionId,
                                 })];
                         case 1:
                             result = _a.sent();
@@ -923,44 +923,44 @@
             });
         };
         DataApiDriver.prototype.startTransaction = function () {
-            return __awaiter(this, void 0, void 0, function () {
-                var transactionId;
-                return __generator(this, function (_a) {
-                    switch (_a.label) {
-                        case 0: return [4 /*yield*/, this.client.beginTransaction()];
-                        case 1:
-                            transactionId = (_a.sent()).transactionId;
-                            this.transactionId = transactionId;
-                            return [2 /*return*/];
-                    }
-                });
-            });
         };
         DataApiDriver.prototype.commitTransaction = function () {
-            return __awaiter(this, void 0, void 0, function () {
-                return __generator(this, function (_a) {
-                    switch (_a.label) {
-                        case 0: return [4 /*yield*/, this.client.commitTransaction({ transactionId: this.transactionId })];
-                        case 1:
-                            _a.sent();
-                            this.transactionId = undefined;
-                            return [2 /*return*/];
-                    }
-                });
-            });
         };
         DataApiDriver.prototype.rollbackTransaction = function () {
-            return __awaiter(this, void 0, void 0, function () {
-                return __generator(this, function (_a) {
-                    switch (_a.label) {
-                        case 0: return [4 /*yield*/, this.client.rollbackTransaction({ transactionId: this.transactionId })];
-                        case 1:
-                            _a.sent();
-                            this.transactionId = undefined;
-                            return [2 /*return*/];
-                    }
-                });
-            });
         };
         return DataApiDriver;
     }());
```

And the errors are gone.

I'll take time ASAP for taking it seriously. If you have any advice, I'm interested.

**Comment by ArsenyYankovsky** [comment]
@LoicMahieu Could you please give a reproducible code so that I can take a look at it? Thanks.

**Comment by LoicMahieu** [comment]
Hi @ArsenyYankovsky 
I can't replicate in development. In seems to be an "environment" issue... I don't know. (We run in Lambda)

I receive a lot of theses errors in Sentry. It appears randomly, I couldn't replicate it myself but my some of my users received this error.
Breadcrumbs from Sentry looks like:
<img width="811" alt="Capture d’écran 2020-01-17 à 15 42 30" src="https://user-images.githubusercontent.com/900947/72620649-043cb900-3940-11ea-9527-c2f812c3797c.png">

Maybe it's appears when multiple transactions are started in parallel ? Needs to find time to investigate...

**Comment by TreeMan360** [comment]
@LoicMahieu although not directly related to your issue. I use transactions in production and have seen no such errors in my logs. I however use https://www.npmjs.com/package/typeorm-transactional-cls-hooked. I path the BaseRepository as described in the docs which works fine for me and makes it a non invasive integration - just add decorators on your root such as a command or service.

**Comment by TreeMan360** [comment]
@LoicMahieu also in development are you hitting a cloud database or a local database instance?

**Comment by ArsenyYankovsky** [comment]
@LoicMahieu I took a look at what could be the reason for an error like that. The code in the TypeORM seems to guard against starting a transaction on a connection twice. We create a new instance of the driver for each connection, and the `transactionId `is stored inside it. I can't really see the reason for that to happen.

If you'd like I'll add additional logs including `transactionId` and some unique `driverId` so we can at least understand what happens.

**Comment by ArsenyYankovsky** [comment]
@LoicMahieu I actually encountered an error like that while using this driver in production. In our case we were using one connection for doing a bunch of queries in parallel. The hack that worked for us was to create a 'connection' for each of the queries. We'll need to come up with a proper fix for this in a driver though.

**Comment by m-p-d** [comment]
@ArsenyYankovsky I'm seeing exactly the same errors as @LoicMahieu originally posted in this thread. Making multiple concurrent calls that execute database writes result in these errors every time:

```MissingRequiredParameter: Missing required key 'transactionId' in params```

or

```Transaction AV2vr/ys8mbQJ29i/RwpOHZRX4a7rYXq1p7QqBk/tWj8mtDlk70PFPb+zhffD8Do/fK0+6oVgHKJGV8J0QE8Ce1xGAbTk+WWPpWhR7hUTWbbNr/xjuHuyLCmkt8qCpAwmUtQW54eIlLC0S4H4awcA8vXmjyzymyppThvbiBuUqhzECvMaUDGDK8= is not found```

Creating a connection for each query is not a possibility in our case. Any update on a fix for this issue?

**Comment by jimsorock** [comment]
@ArsenyYankovsky any update for a proper fix? Also is there any information we can provide?

**Comment by ArsenyYankovsky** [comment]
I found a root cause for this. Unfortunately, the issue lies in the TypeORM part of the code. I will submit a PR in the next couple of days.

**Comment by ArsenyYankovsky** [comment]
I've submitted a PR with a fix [here](https://github.com/typeorm/typeorm/pull/6869).

**Comment by otoivainen** [comment]
Now that this is merged, any chances of finalizing this @ArsenyYankovsky ? Would be really good

**Comment by m-p-d** [comment]
Looks like the TypeORM fix submitted was released yesterday in TypeORM 0.2.30 🥳

**Comment by SethVerishop** [comment]
@ArsenyYankovsky do you feel the typeorm changes resolve the issue? We are using 0.2.31 but noticing a large amount of 'Transaction ... is not found' errors even just a few seconds after creating/starting a transaction on a queryRunner and then trying any query on the queryRunner. I suspect that there may be an issue still in how the transactionId is handled between queries

**Comment by ArsenyYankovsky** [comment]
@SethVerishop I'm not sure if I can reproduce this issue. I have [a test case](https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver/blob/f788412d9db5fb928228d9647ff22d693703d3c5/test/functional/pg/basic/simple-queries.pg-func.test.ts#L72) for this and it seems to work for me now. I'd be happy to fix it if you could provide a reproducible scenario or a test case.

**Comment by ArsenyYankovsky** [comment]
I'm going to close this issue until we have a reproducible case indicating there's an issue.
