### ISSUE TITLE
Question: is Date type supported for Postgresql?

### ISSUE THREAD

**Issue by artem123sh** [ArsenyYankovsky/typeorm-aurora-data-api-driver#51]
Hello,
First of all, thanks a lot for the library, I haven't seen anything like typeorm-aurora-data-api-driver with support for Aurora Serverless PostgreSQL. Thanks for working hard and implementing this solution.

I have a question regarding Date type. I've tried to setup a model with type: Date but received the following error:

`@Column({ type: 'date', nullable: true })`
`date: string;`

> "ERROR: column \"date\" is of type date but expression is of type character varying\n  Hint: You will need to rewrite or cast the expression."

I tried to send a value in "2020-01-01" string format.

> query: INSERT INTO "entitry"("id", "date") VALUES (:param_1, :param_2) -- PARAMETERS: [{"param_1":1,"param_2":"2020-10-17"}]

The same code works fine on postresql started in a docker container. Also I tried to create an entity manually in aws query editor and it also worked with 'YYYY-MM-DD' string. After this I tried to update already existing entity using typeorm and if I provide the same date in 'YYYY-MM-DD' format (typeorm checks what fields should be updated and excluded 'date' field for that case) it works. How typeorm knows the field has the same value in dates column if I provide it in the wrong format/way?
I also looked at tests for typeorm-aurora-data-api-driver and haven't found any for date :)

Thanks a lot for your help.

**Comment by ArsenyYankovsky** [comment]
I've submitted a PR fixing this to the TypeORM repository [here](https://github.com/typeorm/typeorm/pull/7483) and released a new 2.0.0 version of the driver. 

While we're waiting for the TypeORM pull request to be merged and a new release, you can use [my fork of TypeORM](https://github.com/ArsenyYankovsky/typeorm), branch `data-api-prepare-hydrate`.

**Comment by ArsenyYankovsky** [comment]
You don't have to use my fork anymore since new TypeORM 0.3.32 was released. Feel free to comment here or open a new issue if something doesn't work.
