### ISSUE TITLE
Creating connection extremely slow

### ISSUE THREAD

**Issue by bart** [ArsenyYankovsky/typeorm-aurora-data-api-driver#52]
Hey everyone, first of all I want to thank you for this plugin that makes it possible to use Aurora Serverless with Serverless Lambdas - well done! I created a connection manager to handle connections and was wondering about some unusual long Lambda execution times. Reason seems to be creation of an initial data API connection which takes more than 6 seconds. Because Lambdas are stateless EACH Lambda that connects to the DB (which in a real world application is a lot because you have a lot of REST endpoints wich do some stuff in a microservice setup) needs that initial "startup time" which isn't possible in production. So my question is if anyone has a solution to this problem.

My connection manager looks like this:

```
// Database.ts
import {
  Connection,
  createConnection,
  getConnectionManager,
  ConnectionOptions,
} from 'typeorm'
import { User } from '../entities/User'

const connectionManager = getConnectionManager()

export async function getConnection(): Promise<Connection> {
  let connection = null

  if (connectionManager.has('default')) {
    console.log('Re-using connection')
    connection = await connectionManager.get('default')
  } else {
    console.log('Creating new connection') // This takes about 6 seconds
    const connectionOptions: ConnectionOptions =
      process.env.STAGE === 'local'
        ? {
            type: 'mysql',
            host: 'localhost',
            port: 3306,
            username: process.env.DB_USER,
            password: process.env.DB_PASSWORD,
            database: process.env.DB_NAME,
          }
        : {
            type: 'aurora-data-api',
            database: process.env.DB_NAME,
            secretArn: process.env.DB_SECRET_ARN,
            resourceArn: process.env.DB_RESOURCE_ARN,
            region: 'eu-central-1',
          }

    try {
      connection = await createConnection({
        ...connectionOptions,
        entities: [User],
        synchronize: false,
        logging: false,
      })
    } catch (error) {
      console.log(error)
    }
  }

  return connection
}
```

And then in my services I can do something like this:

```
import { getConnection } from './Database'
import { User } from '../entities/User'

[...]

await getConnection()
const repository = getRepository(User)
```

Really appreciate your help, thanks!

**Comment by bart** [comment]
Just want to give a quick update: Looks like the reason is NOT the package itself. Tested it with Sequelize c/o Fyreware/mysql-data-api package which gave a similar result. Reason seems to be the initial Aurora Data API itself so I'll close this issue.

**Comment by ablankenship10** [comment]
Hi @bart I'm noticing the same issue, were you able to find a solution?

**Comment by bart** [comment]
@ablankenship10 The only way to solve this was to put all routes into a single catch-all function so that you only have one function at all. This setup will "cache" your connection so when you keep it warm it won't need to start from cold anymore. This setup felt more like a workaround to me so I ended up switching from Aurora to DynamoDB.

**Comment by ablankenship10** [comment]
Hmm that's disappointing. Thats odd it would even need to "connect" at all using the data-api. I'm also working completely locally with the docker image from https://github.com/koxudaxi/local-data-api/ so there should be no actual spin up time..

**Comment by bart** [comment]
On my local machine it was blazing fast. But as soon as I tested it on AWS startup speed took about 20 to 25 seconds
