### ISSUE TITLE
Is this driver (perhaps data-api-client) unable to handle uuid?

### ISSUE THREAD

**Issue by mlg87** [ArsenyYankovsky/typeorm-aurora-data-api-driver#57]
ive been trying to track down an answer to my issue all day. when running a simple query (looking up a user by id for instance) i am getting this error:
![image](https://user-images.githubusercontent.com/10038207/101314919-cd50e980-3816-11eb-81db-e8cda8bff6fd.png)
i just looked at the [aws js sdk docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDSDataService.html#executeStatement-property) and noticed there is no param type that directly correlates to uuid
![image](https://user-images.githubusercontent.com/10038207/101314751-6d5a4300-3816-11eb-899c-366ef21fe09a.png)
there is also [this note on the aws data api general docs](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html)
![image](https://user-images.githubusercontent.com/10038207/101314850-a5fa1c80-3816-11eb-97a6-a4503fc1a09a.png)

so my question is can this really not handle querying with a uuid?

**Comment by carlocorradini** [comment]
Any update on this issue? 😪

**Comment by ArsenyYankovsky** [comment]
I'm currently working on a fix for this and enum issues, also that will fix how the Data API driver handles date/time-related columns. 
I'm planning to submit a PR to the TypeORM repository and release a new version of the driver early next week . We will have to wait until the PR is merged into TypeORM and TypeORM is released, of course. Until then you will be able to work around the issue by using my fork of TypeORM and the latest client. @carlocorradini

**Comment by carlocorradini** [comment]
> I'm currently working on a fix for this and enum issues, also that will fix how the Data API driver handles date/time-related columns.
> I'm planning to submit a PR to the TypeORM repository and release a new version of the driver early next week . We will have to wait until the PR is merged into TypeORM and TypeORM is released, of course. Until then you will be able to work around the issue by using my fork of TypeORM and the latest client. @carlocorradini

WOW!!! Thanks @ArsenyYankovsky 🤩🤩🤩🤩

**Comment by ArsenyYankovsky** [comment]
I've submitted a PR fixing this to the TypeORM repository [here](https://github.com/typeorm/typeorm/pull/7483) and released a new 2.0.0 version of the driver. 

While we're waiting for the TypeORM pull request to be merged and a new release, you can use [my fork of TypeORM](https://github.com/ArsenyYankovsky/typeorm), branch `data-api-prepare-hydrate`.

**Comment by carlocorradini** [comment]
> I've submitted a PR fixing this to the TypeORM repository [here](https://github.com/typeorm/typeorm/pull/7483) and released a new 2.0.0 version of the driver.
> 
> While we're waiting for the TypeORM pull request to be merged and a new release, you can use [my fork of TypeORM](https://github.com/ArsenyYankovsky/typeorm), branch `data-api-prepare-hydrate`.

I'm having problems with your fork since the Typescript files are not compiled and when trying to run ```npm run compile``` it fails. Can you please provide us with the "compiled" directory so we can directly copy and paste it using you fork without any compilation?
Thanks in advance! 🎊

**Comment by ArsenyYankovsky** [comment]
@carlocorradini Please try "git://github.com/ArsenyYankovsky/typeorm.git#data-api-prepare-hydrate-packaged"

**Comment by carlocorradini** [comment]
> @carlocorradini Please try `"git://github.com/ArsenyYankovsky/typeorm.git#data-api-prepare-hydrate-packaged"`

@ArsenyYankovsky I cannot find the branch :(

**Comment by ArsenyYankovsky** [comment]
@carlocorradini 2.0.3 was released with fixes. I also added test cases and everything should work just fine. The only caveat is that Data API destroys and timezone information always returning date/time columns in UTC.

**Comment by ArsenyYankovsky** [comment]
You don't have to use my fork anymore since new TypeORM 0.3.32 was released. Feel free to comment here or open a new issue if something doesn't work.
