### ISSUE TITLE
Does the TypeORM driver support running TypeORM schema migrations against Aurora Serverless

### ISSUE THREAD

**Issue by ricardoduncan** [ArsenyYankovsky/typeorm-aurora-data-api-driver#60]
I can see that the driver supports querying Aurora Serverless. I have a need to run TypeORM schema migrations against an Aurora Serverless Postgress database using the AWS Data API from a ci server e.g. gitlab.

Is there a way to do that with this driver?

**Comment by ArsenyYankovsky** [comment]
Yes, this should work just fine. Let me know if you have any issues.
