### ISSUE TITLE
Casting of values causes query errors

### ISSUE THREAD

**Issue by Cyberuben** [ArsenyYankovsky/typeorm-aurora-data-api-driver#72]
Hi,

We're using this package to connect to our Aurora serverless database cluster. For testing, we use a local Postgres database and everything works fine. The `transformParameters` in the `PostgresQueryTransformer` incorrectly assumes that our string (which is a valid UUID) should be cast to type `uuid`. The column we're querying is in fact a `character varying` (regular string) as it does not only store UUIDs but also other strings.

Because of this incorrect assumption, we are unable to query our database when the parameter we're using is formatted as an UUID. 

Another issue is that we've got a column specified as `@Column('json') content: SomeType;` which works fine with a regular Postgres connection, but we're prompted with the following error when trying to insert data: `ERROR: column "content" is of type json but expression is of type character varying`

**Comment by seawatts** [comment]
Any progress here?

**Comment by josephktcheung** [comment]
I hit the same issue like what @Cyberuben had on UUID automatic casting. From https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver/blob/b6b1ff112a3540277711590e45743af265f138d3/src/query-transformer/postgres-query-transformer.ts#L172-L178 we use regex to check if a parameter is a UUID-like.

Besides, https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver#automatic-casting said that we can set `formatOptions.castParameters` to false to disable automatic casting, but from https://github.com/jeremydaly/data-api-client/blame/1f2666597eb331580eafbc02d2c3a4fa33bbaeff/README.md#L146 Valid keys are `deserializeDate` and `treatAsLocalDate`, `castParameters` is not shown there.

I wonder how we can express our intent to type cast a parameter when we set `formatOptions.castParameters` to false as well.

**Comment by ArsenyYankovsky** [comment]
Sorry for taking a long time to respond.
I will fix the `json` thing later today or tomorrow.
The UUID hack was put in place to make TypeORM work with UUID primary keys in entities in very simple scenarios. Unfortunately, it doesn't call `preparePersistentValues` to transform a primary key in the Repository.

You can force casting for a parameter like this:

```
const post = await this.postRepository.findOne({
  deviceId: {
    value: uuid,
    cast: 'uuid',
}});
```
I will add this to the documentation.

I'll need to spend some more time to investigate if it's possible to fix it properly so this hack isn't needed.

**Comment by seawatts** [comment]
Thanks for the quick turnaround @ArsenyYankovsky!

I haven't looked much at the code, but would there be a way to define the cast type on the entity level, in the column decorator, or something? Instead of having to cast it on every single query?

**Comment by ArsenyYankovsky** [comment]
I cannot reproduce the `json` part of the issue. Perhaps you could provide a test case or a code example?
Also I added documentation on the parameter casting [here](https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver#parameter-casting).

Casting parameters automatically based on the entity metadata should be possible, but I'm not sure about the amount of changes required in the TypeORM. I didn't find a way to do it when I worked on this, but I admit I didn't look too far. I don't know when I get some time to investigate it as I'm a bit busy right now.

**Comment by seawatts** [comment]
Okay, thanks for the information. The only problem remaining for me is that it's trying to auto-cast UUID and I have so many queries all over my app it would be very difficult to replace them all to turn off the autocast. I also have ENUMS though that I do want to auto cast. I'm in a tricky situation lol

**Comment by Cyberuben** [comment]
@ArsenyYankovsky thanks for the response. I'll see if I can reproduce the JSON issue. It only occurred after I was trying to work around the UUID situation and a coworker upgraded the version from 0.2.31 to 0.2.32, so it might have been fixed in that version or it was something on our end.

**Comment by seawatts** [comment]
@Cyberuben did you find a workaround for the UUID issue?

**Comment by josephktcheung** [comment]
@seawatts here's how I workaround it

```ts
const existingDevice = await this.devicesRepository.findOne({
  where: {
    deviceId: Raw(`'${deviceId}'`),
  },
});
```

**Comment by seawatts** [comment]
Ah ha, thanks for sharing! I'll have to go update my entire codebase to do that. Which is less than ideal. I'm going to hold off to see if there is a better solution.

**Comment by ArsenyYankovsky** [comment]
@seawatts I decided to remove the UUID hack as it does more harm than good. It is removed in the 2.1.0 version of the driver.

**Comment by seawatts** [comment]
Wow thanks @ArsenyYankovsky! I'll try it out soon and let you know. If this works I'll be able to finally set up my serverless DB in prod 😁🚀 you're the man!
