### ISSUE TITLE
support of continueAfterTimeout param

### ISSUE THREAD

**Issue by lielran** [ArsenyYankovsky/typeorm-aurora-data-api-driver#82]
`continueAfterTimeout` is supported by AWS Aurora Data Api as well as https://github.com/jeremydaly/data-api-client. 

I saw this issue (and PR) but ti was closed without any workaround or impl 
https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver/issues/55

**Comment by ArsenyYankovsky** [comment]
@lielran Have you tried passing this option in the `serviceConfigOptions`?

**Comment by lielran** [comment]
from the docs in the data-api-client 
it seems like a param on the query level and not on the connection level. 
I've tried to pass it with `true` and others but failed to do so. 

can you provide a sample that works for you?

**Comment by ArsenyYankovsky** [comment]
Yes, you're correct.
What would be a preferred solution here? Perhaps make it a connection parameter and apply on each query?

**Comment by lielran** [comment]
Both sounds great actaully. usally it more of query level since the connection can be resue to other usecases. 

can you point me to the areas that you think it should be impl?
