### ISSUE TITLE
ERROR: operator does not exist: uuid = character varying Or ERROR: column "mediaType" is of type medias_mediatype_enum but expression is of type character varying

### ISSUE THREAD

**Issue by muaaztkxel** [ArsenyYankovsky/typeorm-aurora-data-api-driver#85]
I am using
 - Node [14]
 - Server-less [2.41.1]
 - Database Engine: [aws-aurora-postgres]
 - TypeORM Version: [0.2.32]
 - Driver Version [2.1.0]

I am getting this error "**ERROR: operator does not exist: uuid = character varying**"  When i try to find a record or try to save the record. If I downgrade the driver to "2.0.0" i dont get this error but then i started getting errors abount enum type casting. Error is  "**ERROR: column "mediaType" is of type medias_mediatype_enum but expression is of type character varying**".

It worked fine with node and express project but started causing issues on Server-less Project which is using Typescript, and Webpack

**I have set the formatOptions in connection options as** 
```
formatOptions: {
    // additional format options to pass to the Data API client
    castParameters: true,
}
```

**This is my Root Entity**
```
import {
  Column,
  CreateDateColumn,
  DeleteDateColumn,
  ManyToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { Brand, Nullable } from '../types';
import { EntityUsers } from './users.entity';

export abstract class RootEntity<X extends Brand<string, string>> {
  @PrimaryGeneratedColumn('uuid')
  id!: X;

  @ManyToOne('EntityUsers')
  createdBy!: EntityUsers;

  @Column({ nullable: false })
  createdById!: EntityUsers['id'];

  @CreateDateColumn()
  createdAt!: Date;

  @DeleteDateColumn()
  deletedDate!: Date;
}

export interface IRootHistory<
  U extends Brand<string, string>,
  T extends RootEntity<U>
> {
  recordId: U;
}
```

**here it is my actual entitiy**
```
import { Column, Entity, PrimaryGeneratedColumn, VersionColumn } from 'typeorm';
import { ONE_LINK_STAN_LENGTH } from '../constants/db-constants';
import { Brand } from '../types';
import { RootEntity } from './root-entity';

export type EntityOneLinkStanCountersId = Brand<
  string,
  'OneLinkStanCountersId'
>;

abstract class EntityOneLinkStanCountersBase {
  @PrimaryGeneratedColumn('uuid')
  id!: EntityOneLinkStanCountersId;

  @Column({ type: 'date', nullable: false })
  date!: Date;

  @Column({ type: 'integer', width: ONE_LINK_STAN_LENGTH, nullable: false })
  counter!: number;
}

@Entity('oneLinkStanCounters')
export class EntityOneLinkStanCounters extends EntityOneLinkStanCountersBase {
  @VersionColumn()
  version!: number;
}

```

This is how i am trying to get data 
```
import { getRepository } from 'typeorm';


const StanRepository = getRepository(EntityOneLinkStanCounters);
  const stan = await StanRepository.findOne({ id });
  if (!stan) return null;
  return stan;

```

**Comment by ArsenyYankovsky** [comment]
Please take a look at the [parameter casting here](https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver#parameter-casting)

**Comment by feroz-shamsi** [comment]
When this will work like normal typeorm ? 
parameter casting doesn't work everywhere.
for now we are using query Builder everywhere but that's slowing us down in development.

**my question is when this will be integrated fully with typeorm so we dont have to cast it or use query builder ?**

**Comment by ghaniev** [comment]
@feroz-shamsi go ahead and contribute, whats problem?

**Comment by feroz-shamsi** [comment]
only if I had time or my manager allow me to, I will definitely contribute to this & typeorm so others don't suffer the same.

**Comment by ghaniev** [comment]
tell your manager if he wants to have a good product he needs to spend resources on open source support

**Comment by ejaz1977pk** [comment]
@ghaniev Hi Ghaniev

First, thank you for informing about the value for contributions to open source projects as well as the role of ownership, however the underlying question here is pertaining to the possible fix of the issue, if it is part of ay of the release. 

If it isn't, the answer is a simple no.
