### ISSUE TITLE
BadRequestException: FATAL: password authentication failed for user "masteruser"

### ISSUE THREAD

**Issue by shaheerizharReal** [ArsenyYankovsky/typeorm-aurora-data-api-driver#86]
**Package versions and database engine type (please complete the following information):**
 - Database Engine: [postgres]
 - TypeORM Version: [0.2.32]
 - Driver Version [2.1.0]

Whenever i try to execute any typeorm query i get this error. "BadRequestException: FATAL: password authentication failed for user "masteruser" from aws-sdk
code breaks at  user = await userRepo.findOne({ email });
![screenshot2](https://user-images.githubusercontent.com/60912927/119439035-f02a7800-bd3a-11eb-8cec-76ed241301f5.png)

![screeenshot3](https://user-images.githubusercontent.com/60912927/119439032-edc81e00-bd3a-11eb-8c6e-87748b7cfaf7.png)
![screenshot1](https://user-images.githubusercontent.com/60912927/119439034-ef91e180-bd3a-11eb-8048-d8c70e071df3.png)

**Comment by ArsenyYankovsky** [comment]
Please make sure that you can connect to your database cluster using credentials from the secret.
